name: CI

on:
  push:
    branches: [ master ]
    tags: [ "v*" ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# ── Define Sepolia-specific env once and reuse it ─────────────────────
env:
  SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}

jobs:
  # ────────────────────────────────── Unit tests (no secrets) ─────────
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm run compile
      - run: npm test

  # ─────────────────────────────── Integration on Sepolia ─────────────
  integration:
    needs: test
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: npm run compile
      - name: Deploy to Sepolia (test)
        run: npx hardhat run scripts/deploy.ts --network sepolia
      - name: Integration tests (Sepolia)
        run: npx hardhat test --network sepolia

  # ─────────────────────────────── Deploy to Sepolia on tag ───────────
  deploy:
    needs: integration
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: npm run compile
      - name: Deploy to Sepolia
        run: |
          npx hardhat run scripts/deploy.ts --network sepolia | tee deploy.log
      - name: Verify on Etherscan
        run: |
          ADDR=$(grep -Eo '0x[a-fA-F0-9]{40}' deploy.log | head -n1)
          npx hardhat verify --network sepolia "$ADDR" "Hello, Hardhat!"
